on:
  workflow_dispatch: {}
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Create a pull-request towards the develop branch
        id: cpr1
        env:
          GITHUB_TOKEN: ${{ secrets.HRA_GITHUB_TOKEN }}
        run: |
          set -euE -o pipefail

          if gh pr view develop -q '.number' --json 'number' > pr-number; then
            echo "::set-output name=pull-request-number::$(cat pr-number)"
          else
            gh pr create \
              --title "Merge develop back into main" \
              --label release \
              --base main --head develop \
              --body 'this pull-request was automatically triggered by a change to the develop branch to keep the main branch up-to-date.' 2>&1 | tee gh-pr-create.log

            pull_request_number="$(tail -n1 gh-pr-create.log | grep -oE '[0-9]+$')"
            echo "::set-output name=pull-request-number::${pull_request_number}"
          fi
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.HRA_GITHUB_TOKEN}}
          pull-request-number: ${{ steps.cpr1.outputs.pull-request-number }}
          merge-method: merge
      - name: Auto approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr1.outputs.pull-request-number }}
